# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'transposition_cipher.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(160, 240, 104, 71))
        self.textEdit.setObjectName("textEdit")
        self.keyEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.keyEdit.setGeometry(QtCore.QRect(360, 250, 113, 20))
        self.keyEdit.setObjectName("keyEdit")
        self.processButton = QtWidgets.QPushButton(self.centralwidget)
        self.processButton.setGeometry(QtCore.QRect(290, 340, 75, 23))
        self.processButton.setObjectName("processButton")
        self.encryptButton = QtWidgets.QRadioButton(self.centralwidget)
        self.encryptButton.setGeometry(QtCore.QRect(170, 130, 91, 21))
        self.encryptButton.setObjectName("encryptButton")
        self.decryptButton = QtWidgets.QRadioButton(self.centralwidget)
        self.decryptButton.setGeometry(QtCore.QRect(350, 130, 91, 21))
        self.decryptButton.setObjectName("decryptButton")
        self.resultEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.resultEdit.setGeometry(QtCore.QRect(290, 440, 104, 71))
        self.resultEdit.setObjectName("resultEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(196, 0, 321, 61))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(160, 220, 101, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(290, 420, 111, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(400, 230, 47, 13))
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.processButton.setText(_translate("MainWindow", "запуск"))
        self.encryptButton.setText(_translate("MainWindow", "зашифровать"))
        self.decryptButton.setText(_translate("MainWindow", "дешифровать"))
        self.label.setText(_translate("MainWindow", "Шифратор/Дешифратор. Транспозиционный строчный шифр"))
        self.label_2.setText(_translate("MainWindow", "вводное сообщение"))
        self.label_3.setText(_translate("MainWindow", "выходное сообщение"))
        self.label_4.setText(_translate("MainWindow", "ключ"))
